# Generated by Django 4.2.4 on 2023-10-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='catagory',
            field=models.IntegerField(choices=[(1, 'Bento'), (2, 'Drink'), (3, 'Other')], default=1),
            preserve_default=False,
        ),
    ]
