# Generated by Django 4.2.4 on 2023-10-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
